### PR TITLE
Fixed automatic factory shutdown bug #58

### PR DESCRIPTION
**Pull request by nnseva**
I am not sure that my way of reactor shutting downing check is a good enough, but didn't found a right one for twisted unittest package.

### CODE REVIEW

**Comment by smira** [comment]
@nnseva please take a look at Travis CI - pep8 is broken. Test LGTM

**Comment by nnseva** [comment]
Hi, I meant the file name (test_z_...) there. Really I don't know how to test the reactor shutdowning procedure correctly. I don't see any such a test in your code, so the registerForShutdonw has not been tested at all before my fix.

The following warning in the travis build logs is about the same:
/home/travis/build/smira/txZMQ/txzmq/test/test_z_reactor_shutdown.py:25: DeprecationWarning: reactor.stop cannot be used inside unit tests. In the future, using stop will fail the test and may crash or hang the test run.

**Comment by nnseva** [comment]
I didn't found any information how to test reactor shutdown procedure in unittest https://twistedmatrix.com/documents/12.0.0/core/howto/testing.html

"Leave the Reactor as you found it" but I can not, just because I am trying to test the reactor shutdown, and it can not be undone.

Do you have any suggestions?

**Comment by nnseva** [comment]
Yes, i've found it

**Comment by nnseva** [comment]
Oh, nooo ... the good way is a bad one because it doesn't reproduce the bug!

**Comment by nnseva** [comment]
Reproduced now! It's final

**Comment by nnseva** [comment]
@smira what about to merge the request?

**Comment by smira** [comment]
@nnseva sorry took longer than I expected to get back here

**Comment by smira** [comment]
Release 0.7.4 with latest changes.

**Pull request merged**
